/**
 * What `npm run db:seed-site` writes. Generated by the new-site skill from the
 * interview answers; edit freely — it is only read by src/site-seed/cli.ts.
 */
export const LOCALES = ["el","en"] as const;
export const DEFAULT_LOCALE = 'el';

/** Site settings, always upserted. Booking kinds are formatted by the CLI. */
export const SETTINGS: ReadonlyArray<readonly [string, unknown]> = [
  [
    "site.supportEmail",
    "info@demo-site.gr"
  ],
  [
    "module.commerce",
    true
  ],
  [
    "module.booking",
    false
  ],
  [
    "module.forms",
    true
  ],
  [
    "module.seo",
    true
  ],
  [
    "module.newsletter",
    true
  ],
  [
    "module.customers",
    true
  ],
  [
    "module.googleReviews",
    false
  ],
  [
    "module.popups",
    false
  ],
  [
    "module.media",
    true
  ],
  [
    "module.pm",
    false
  ],
  [
    "ecommerce.currency",
    "EUR"
  ],
  [
    "ecommerce.paymentProvider",
    "manual"
  ]
];

/** `booking.kinds`, or null to leave every kind available. */
export const BOOKING_KINDS: readonly string[] | null = null;

export interface SeedPage {
  slug: string;
  title: Record<string, string>;
  body: Record<string, string>;
}

/** The base pages. `home` is served at `/`; the others at `/{slug}` (contact at /contact). */
export const PAGES: SeedPage[] = [
  {
    "slug": "home",
    "title": {
      "el": "Demo Site",
      "en": "Demo Site"
    },
    "body": {
      "el": "Καλώς ήρθατε στο Demo Site.",
      "en": "Welcome to Demo Site."
    }
  },
  {
    "slug": "about",
    "title": {
      "el": "Σχετικά με εμάς",
      "en": "About us"
    },
    "body": {
      "el": "Προσωρινό κείμενο — πείτε στους επισκέπτες ποιοι είστε και τι κάνετε.",
      "en": "Placeholder — tell visitors who you are and what you do."
    }
  },
  {
    "slug": "contact",
    "title": {
      "el": "Επικοινωνία",
      "en": "Contact"
    },
    "body": {
      "el": "Προσωρινό κείμενο — μία-δύο γραμμές πάνω από τη φόρμα επικοινωνίας.",
      "en": "Placeholder — a line or two above the contact form."
    }
  },
  {
    "slug": "privacy",
    "title": {
      "el": "Πολιτική απορρήτου",
      "en": "Privacy policy"
    },
    "body": {
      "el": "Προσωρινό κείμενο — αντικαταστήστε το με την πολιτική απορρήτου πριν το λανσάρισμα.",
      "en": "Placeholder — replace with your privacy policy before launch."
    }
  },
  {
    "slug": "terms",
    "title": {
      "el": "Όροι χρήσης",
      "en": "Terms of use"
    },
    "body": {
      "el": "Προσωρινό κείμενο — αντικαταστήστε το με τους όρους χρήσης πριν το λανσάρισμα.",
      "en": "Placeholder — replace with your terms before launch."
    }
  }
];

/** Which sample documents to create, one of each. */
export const SAMPLES = {
  product: true,
  bookingKind: null as string | null,
  article: true,
  answer: true,
  scenario: true,
};
